# Generated by Django 5.0 on 2024-03-12 23:24

import gooseApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gooseApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='background_image',
            field=models.ImageField(default=None, upload_to=gooseApp.models.user_directory_background_pic),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(default=None, upload_to=gooseApp.models.user_directory_prof_pic),
        ),
    ]
