# Generated by Django 5.0 on 2024-04-04 02:38

import gooseApp.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gooseApp', '0002_alter_profile_background_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='background_image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=gooseApp.models.user_directory_background_pic),
        ),
        migrations.AlterField(
            model_name='profile',
            name='following',
            field=models.ManyToManyField(blank=True, null=True, related_name='following', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=gooseApp.models.user_directory_prof_pic),
        ),
    ]
